trigger:
- master

jobs:

- job: 'Run'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: PowerShell@2
    inputs:
      targetType: filePath
      filePath: 'getLatestBuild.ps1'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - powershell: New-Item -ItemType "directory" -Path "$env:JOBSFOLDER"

  - task: DownloadPipelineArtifact@1
    continueOnError: true
    inputs:
      buildType: 'specific'
      definition: $(System.DefinitionId)
      project: $(System.TeamProjectId)
      buildVersionToDownload : 'specific'
      buildId: $(lastBuild)
      artifactName: JobsOutput
      downloadPath: $(Build.SourcesDirectory)

  - script: python3 -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python3 amazon.py $(slackHookVirtual) '$(queryVirtual)' '$(jobsFolder)/$(jobsVirtual)'
    displayName: 'Finding Virtual Jobs'

  - script: python3 amazon.py $(slackHookMinneapolis) '$(queryMinneapolis)' '$(jobsFolder)/$(jobsMinneapolis)'
    displayName: 'Finding Minneapolis Jobs'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'JobsOutput' 
      targetPath: '$(jobsFolder)'
